services:
  pnos:
    build: .
    image: registry.cn-hangzhou.aliyuncs.com/pandanetos/PNOS-docker:latest
    container_name: pnos
    restart: unless-stopped
    ports:
      - "5540:80"
    volumes:
      - ./data:/data
      - ./media:/media
