name: Build & Push PNOS-docker Docker Image

on:
  workflow_dispatch:
    inputs:
      web_version:
        description: "pnos-web 版本号（如 v0.1.0）"
        default: "latest"
        required: false
      runtime_version:
        description: "pnos-runtime 版本号（如 v0.1.0）"
        default: "latest"
        required: false

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: PandaNetOS/PandaNetOS/.github/workflows/reusable-release-docker-image.yml@main
    with:
      image_name: PNOS-docker
      platforms: linux/amd64
      push_to_ghcr: true
      push_to_dockerhub: true
      push_to_aliyun: true
      tag_latest: true
      tag_sha: true
      custom_tags: |
        type=raw,value=front-${{ github.event.inputs.web_version }}_backend-${{ github.event.inputs.runtime_version }}
      build_args: '{"WEB_VERSION":"${{ github.event.inputs.web_version }}","RUNTIME_VERSION":"${{ github.event.inputs.runtime_version }}"}'
      provenance: false
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      ALIYUN_ACR_REGISTRY: ${{ secrets.ALIYUN_ACR_REGISTRY }}
      ALIYUN_ACR_NAMESPACE: ${{ secrets.ALIYUN_ACR_NAMESPACE }}
      ALIYUN_ACR_USERNAME: ${{ secrets.ALIYUN_ACR_USERNAME }}
      ALIYUN_ACR_PASSWORD: ${{ secrets.ALIYUN_ACR_PASSWORD }}
